name: Docker Build Ubuntu 22.04

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU Virtualization for buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: docker
        run: |
          docker buildx build . -f pygmtsar.ubuntu2204.Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag pechnikov/pygmtsar:$(date "+%Y-%m-%d") \
            --tag pechnikov/pygmtsar:latest \
            --pull --push --no-cache
