# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS tests

on:
  push:
    branches: [ "pygmtsar2" ]
  pull_request:
    branches: [ "pygmtsar2" ]

permissions:
  contents: read

jobs:
  Pico_do_Fogo_2014:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        uname -a
        # prepare system
        brew install wget libtiff hdf5 gmt ghostscript autoconf
    - name: Compile GMTSAR
      run: |
        git config --global advice.detachedHead false
        git clone --branch master https://github.com/gmtsar/gmtsar GMTSAR
        cd GMTSAR
        git checkout e98ebc0f4164939a4780b1534bac186924d7c998
        autoconf
        ./configure --with-orbits-dir=/tmp
        make
        make install
        export PATH=$PATH:${{ github.workspace }}/GMTSAR/bin
        # check installation
        echo "Show compilation directory"
        pwd
        echo "Set PATH"
        echo "$PATH"
        echo "Run gmtsar_sharedir.csh"
        gmtsar_sharedir.csh
        echo "Run make_s1a_tops"
        make_s1a_tops
    - name: Install PyGMTSAR
      run: |
        pip3 install pyvista panel
        pip3 install -e ./pygmtsar/
    - name: Run test
      working-directory: tests
      run: |
        export PATH=$PATH:/Users/runner/work/gmtsar/gmtsar/GMTSAR/bin
        ulimit -n 10000
        # remove Google Colab specific commands and add __main__ section
        cat pico_do_fogo_volcano_eruption_2014.py \
            | sed '/if \x27google\.colab\x27 in sys\.modules:/,/^$/d' \
            | sed 's/^[[:blank:]]*!.*$//' \
            | awk '/username = \x27GoogleColab2023\x27/ {print "if __name__ == \x27__main__\x27:"; indent=1} {if(indent) sub(/^/, "    "); print}' \
            > pico_do_fogo_volcano_eruption_2014.fixed.py
        python3 pico_do_fogo_volcano_eruption_2014.fixed.py
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: Plots (${{ matrix.os }}, ${{ matrix.python-version }})
        path: tests/*.jpg
        if-no-files-found: error
