# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu tests

on:
  push:
    branches: [ "pygmtsar2" ]
  pull_request:
    branches: [ "pygmtsar2" ]

permissions:
  contents: read

jobs:
  Imperial_Valley_2015:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        uname -a
        # prepare system
        sudo apt update
        # https://github.com/gmtsar/gmtsar/wiki/GMTSAR-Wiki-Page
        sudo apt install -y csh subversion autoconf libtiff5-dev libhdf5-dev wget
        sudo apt install -y liblapack-dev
        sudo apt install -y gfortran
        sudo apt install -y g++
        sudo apt install -y libgmt-dev
        sudo apt install -y gmt-dcw gmt-gshhg
        # gmt-gshhg-full should be installed automatically (it is required to use GMTSAR landmask)
        sudo apt install -y gmt
        # add missed package
        sudo apt install -y make
        # vtk rendering
        sudo apt install -y xvfb
    - name: Compile GMTSAR
      run: |
        git config --global advice.detachedHead false
        git clone --branch master https://github.com/gmtsar/gmtsar GMTSAR
        cd GMTSAR
        git checkout e98ebc0f4164939a4780b1534bac186924d7c998
        autoconf
        ./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
        make CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
        make install
        # check installation
        export PATH=$PATH:/home/runner/work/gmtsar/gmtsar/GMTSAR/bin
        echo "Start gmtsar_sharedir.csh"
        gmtsar_sharedir.csh
    - name: Install PyGMTSAR
      run: |
        # upgrade package to resolve dependencies
        #pip3 install click --upgrade
        #pip3 install matplotlib seaborn
        # vtk rendering
        pip3 install pyvista
        pip3 install -e ./pygmtsar/
    - name: Run test
      working-directory: tests
      run: |
        export PATH=$PATH:/home/runner/work/gmtsar/gmtsar/GMTSAR/bin
        Xvfb :99 -screen 0 800x600x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        export XVFB_PID=$!
        python3 imperial_valley_2015.py
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: Plots (${{ matrix.os }}, ${{ matrix.python-version }})
        path: tests/*.jpg
        if-no-files-found: error
